"""Add contact_number and email_id to User model

Revision ID: 38b075a6ba6b
Revises: 014a7bda3e9b
Create Date: 2024-11-19 23:09:59.580349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b075a6ba6b'
down_revision = '014a7bda3e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('ear_changes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('drowsiness_alert')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drowsiness_alert', sa.VARCHAR(length=120), nullable=True))
        batch_op.alter_column('ear_changes',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
